/** @format */

type Theme = {
  name: string;
  preview: string;
  background: string;
  accent: `#${string}`;
  type: "dark" | "light";
  navbar: { tint: { color: `#${string}`; opacity: number }; blur: string };
  sidebar: { tint: { color: `#${string}`; opacity: number }; blur: string };
  playbar: { tint: { color: `#${string}`; opacity: number }; blur: string };
  overall: { tint: { color: `#${string}`; opacity: number }; blur: string };
  viewport: { tint: { color: `#${string}`; opacity: number }; blur: string };
};

export const themes = [
  {
    preview: "",
    type: "dark",
    accent: "#82B4C9",
    name: "brook",
    background: "brook.jpg",
    navbar: { tint: { color: "#000000", opacity: 0.3 }, blur: "15px" },
    sidebar: { tint: { color: "#000000", opacity: 0.3 }, blur: "15px" },
    playbar: { tint: { color: "#000000", opacity: 0.3 }, blur: "15px" },
    overall: { tint: { color: "#000000", opacity: 0.5 }, blur: "15px" },
    viewport: { tint: { color: "#000000", opacity: 0.0 }, blur: "00px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#FF7722",
    name: "pumpkin orange",
    background: "pumpkin-orange.jpg",
    navbar: { tint: { color: "#000000", opacity: 0.3 }, blur: "15px" },
    sidebar: { tint: { color: "#000000", opacity: 0.3 }, blur: "15px" },
    playbar: { tint: { color: "#000000", opacity: 0.3 }, blur: "15px" },
    overall: { tint: { color: "#000000", opacity: 0.5 }, blur: "15px" },
    viewport: { tint: { color: "#000000", opacity: 0.0 }, blur: "00px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#FF9922",
    name: "pumpkin yellow",
    background: "pumpkin-yellow.jpg",
    navbar: { tint: { color: "#000000", opacity: 0.3 }, blur: "15px" },
    sidebar: { tint: { color: "#000000", opacity: 0.3 }, blur: "15px" },
    playbar: { tint: { color: "#000000", opacity: 0.3 }, blur: "15px" },
    overall: { tint: { color: "#000000", opacity: 0.5 }, blur: "15px" },
    viewport: { tint: { color: "#000000", opacity: 0.0 }, blur: "00px" },
  },
  {
    preview: "",
    type: "light",
    accent: "#588888",
    name: "white flowers",
    background: "white-flowers.jpg",
    navbar: { tint: { color: "#ABBBBB", opacity: 0.1 }, blur: "10px" },
    sidebar: { tint: { color: "#ABBBBB", opacity: 0.1 }, blur: "10px" },
    playbar: { tint: { color: "#ABBBBB", opacity: 0.1 }, blur: "10px" },
    overall: { tint: { color: "#FFFFFF", opacity: 0.5 }, blur: "10px" },
    viewport: { tint: { color: "#FFFFFF", opacity: 0.0 }, blur: "00px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#FF88BB",
    name: "cherry blossom",
    background: "cherry-blossom.jpg",
    navbar: { tint: { color: "#000000", opacity: 0.2 }, blur: "10px" },
    sidebar: { tint: { color: "#000000", opacity: 0.2 }, blur: "10px" },
    playbar: { tint: { color: "#000000", opacity: 0.2 }, blur: "10px" },
    overall: { tint: { color: "#000000", opacity: 0.5 }, blur: "10px" },
    viewport: { tint: { color: "#000000", opacity: 0 }, blur: "00px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#99CC22",
    name: "green leaves",
    background: "green-leaves.jpg",
    navbar: { tint: { color: "#000000", opacity: 0.2 }, blur: "10px" },
    sidebar: { tint: { color: "#000000", opacity: 0.2 }, blur: "10px" },
    playbar: { tint: { color: "#000000", opacity: 0.2 }, blur: "10px" },
    overall: { tint: { color: "#000000", opacity: 0.5 }, blur: "10px" },
    viewport: { tint: { color: "#000000", opacity: 0 }, blur: "00px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#AA53BB",
    name: "violet flowers",
    background: "violet-flowers.jpg",
    navbar: { tint: { color: "#000000", opacity: 0.2 }, blur: "10px" },
    sidebar: { tint: { color: "#000000", opacity: 0.2 }, blur: "10px" },
    playbar: { tint: { color: "#000000", opacity: 0.2 }, blur: "10px" },
    overall: { tint: { color: "#202020", opacity: 0.8 }, blur: "10px" },
    viewport: { tint: { color: "#000000", opacity: 0.0 }, blur: "00px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#82FFC9",
    name: "kuroshitsuji",
    background: "kuroshitsuji.png",
    navbar: { tint: { color: "#000000", opacity: 0.3 }, blur: "10px" },
    sidebar: { tint: { color: "#000000", opacity: 0.3 }, blur: "10px" },
    playbar: { tint: { color: "#000000", opacity: 0.3 }, blur: "10px" },
    overall: { tint: { color: "#000000", opacity: 0.5 }, blur: "5px" },
    viewport: { tint: { color: "#000000", opacity: 0 }, blur: "00px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#9988FF",
    name: "purple blue leaves",
    background: "purple-blue-leaves.png",
    navbar: { tint: { color: "#000000", opacity: 0.3 }, blur: "10px" },
    sidebar: { tint: { color: "#000000", opacity: 0.3 }, blur: "10px" },
    playbar: { tint: { color: "#000000", opacity: 0.3 }, blur: "10px" },
    overall: { tint: { color: "#000000", opacity: 0.5 }, blur: "8px" },
    viewport: { tint: { color: "#000000", opacity: 0 }, blur: "00px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#AA88CC",
    name: "boobs",
    background: "https://cdn.hentaigifz.com/82570/anime-boobs.gif",
    navbar: { tint: { color: "#000000", opacity: 0.3 }, blur: "10px" },
    sidebar: { tint: { color: "#000000", opacity: 0.3 }, blur: "10px" },
    playbar: { tint: { color: "#000000", opacity: 0.3 }, blur: "10px" },
    overall: { tint: { color: "#000000", opacity: 0.5 }, blur: "12px" },
    viewport: { tint: { color: "#000000", opacity: 0 }, blur: "00px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#FF2222",
    name: "red guitarist",
    background: "red-guitarist.png",
    navbar: { tint: { color: "#000000", opacity: 0.4 }, blur: "10px" },
    sidebar: { tint: { color: "#000000", opacity: 0.4 }, blur: "10px" },
    playbar: { tint: { color: "#000000", opacity: 0.4 }, blur: "10px" },
    overall: { tint: { color: "#0a0a0a85", opacity: 0.5 }, blur: "10px" },
    viewport: { tint: { color: "#000000", opacity: 0.0 }, blur: "00px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#83BDF4",
    name: "sakata gintoki",
    background: "sakata-gintoki.jpg",
    navbar: { tint: { color: "#83BDF4", opacity: 0.05 }, blur: "10px" },
    sidebar: { tint: { color: "#83BDF4", opacity: 0.05 }, blur: "10px" },
    playbar: { tint: { color: "#83BDF4", opacity: 0.05 }, blur: "10px" },
    overall: { tint: { color: "#000000", opacity: 0.7 }, blur: "10px" },
    viewport: { tint: { color: "#000000", opacity: 0.0 }, blur: "00px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#83BDF4CC",
    name: "sakata gintoki 2",
    background: "https://images7.alphacoders.com/137/thumb-1920-1374435.png",
    navbar: { tint: { color: "#83BDF4", opacity: 0.05 }, blur: "0px" },
    sidebar: { tint: { color: "#83BDF4", opacity: 0.05 }, blur: "0px" },
    playbar: { tint: { color: "#83BDF4", opacity: 0.05 }, blur: "0px" },
    overall: { tint: { color: "#000000", opacity: 0.7 }, blur: "0px" },
    viewport: { tint: { color: "#000000", opacity: 0.0 }, blur: "0px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#F4BF50",
    name: "sakata kintoki 3",
    background: "https://images5.alphacoders.com/113/thumb-1920-1137590.png",
    navbar: { tint: { color: "#F4BF50", opacity: 0.05 }, blur: "00px" },
    sidebar: { tint: { color: "#F4BF50", opacity: 0.05 }, blur: "00px" },
    playbar: { tint: { color: "#F4BF50", opacity: 0.05 }, blur: "00px" },
    overall: { tint: { color: "#000000", opacity: 0.7 }, blur: "00px" },
    viewport: { tint: { color: "#000000", opacity: 0.0 }, blur: "00px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#F4BF50",
    name: "sakata kintoki",
    background: "sakata-kintoki.png",
    navbar: { tint: { color: "#F4BF50", opacity: 0.05 }, blur: "10px" },
    sidebar: { tint: { color: "#F4BF50", opacity: 0.05 }, blur: "10px" },
    playbar: { tint: { color: "#F4BF50", opacity: 0.05 }, blur: "10px" },
    overall: { tint: { color: "#000000", opacity: 0.7 }, blur: "10px" },
    viewport: { tint: { color: "#000000", opacity: 0.0 }, blur: "00px" },
  },
] satisfies Theme[];
