/** @format */

import { createGlobalStore } from "./create";

type Theme = {
  name: string;
  preview: string;
  background: string;
  accent: `#${string}`;
  type: "dark" | "light";
  navbar: { tint: { color: `#${string}`; opacity: number }; blur: string };
  sidebar: { tint: { color: `#${string}`; opacity: number }; blur: string };
  playbar: { tint: { color: `#${string}`; opacity: number }; blur: string };
  overall: { tint: { color: `#${string}`; opacity: number }; blur: string };
  viewport: { tint: { color: `#${string}`; opacity: number }; blur: string };
};

export const themes = [
  {
    preview: "",
    type: "dark",
    accent: "#82B4C9",
    name: "brook",
    background: "brook.jpg",
    navbar: { tint: { color: "#000000", opacity: 0.3 }, blur: "15px" },
    sidebar: { tint: { color: "#000000", opacity: 0.3 }, blur: "15px" },
    playbar: { tint: { color: "#000000", opacity: 0.3 }, blur: "15px" },
    overall: { tint: { color: "#000000", opacity: 0.5 }, blur: "15px" },
    viewport: { tint: { color: "#000000", opacity: 0.0 }, blur: "00px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#FF7722",
    name: "pumpkin orange",
    background: "pumpkin-orange.jpg",
    navbar: { tint: { color: "#000000", opacity: 0.3 }, blur: "15px" },
    sidebar: { tint: { color: "#000000", opacity: 0.3 }, blur: "15px" },
    playbar: { tint: { color: "#000000", opacity: 0.3 }, blur: "15px" },
    overall: { tint: { color: "#000000", opacity: 0.5 }, blur: "15px" },
    viewport: { tint: { color: "#000000", opacity: 0.0 }, blur: "00px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#FF9922",
    name: "pumpkin yellow",
    background: "pumpkin-yellow.jpg",
    navbar: { tint: { color: "#000000", opacity: 0.3 }, blur: "15px" },
    sidebar: { tint: { color: "#000000", opacity: 0.3 }, blur: "15px" },
    playbar: { tint: { color: "#000000", opacity: 0.3 }, blur: "15px" },
    overall: { tint: { color: "#000000", opacity: 0.5 }, blur: "15px" },
    viewport: { tint: { color: "#000000", opacity: 0.0 }, blur: "00px" },
  },
  {
    preview: "",
    type: "light",
    accent: "#588888",
    name: "white flowers",
    background: "white-flowers.jpg",
    navbar: { tint: { color: "#ABBBBB", opacity: 0.1 }, blur: "10px" },
    sidebar: { tint: { color: "#ABBBBB", opacity: 0.1 }, blur: "10px" },
    playbar: { tint: { color: "#ABBBBB", opacity: 0.1 }, blur: "10px" },
    overall: { tint: { color: "#FFFFFF", opacity: 0.5 }, blur: "10px" },
    viewport: { tint: { color: "#FFFFFF", opacity: 0.0 }, blur: "00px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#FF88BB",
    name: "cherry blossom",
    background: "cherry-blossom.jpg",
    navbar: { tint: { color: "#000000", opacity: 0.2 }, blur: "10px" },
    sidebar: { tint: { color: "#000000", opacity: 0.2 }, blur: "10px" },
    playbar: { tint: { color: "#000000", opacity: 0.2 }, blur: "10px" },
    overall: { tint: { color: "#000000", opacity: 0.5 }, blur: "10px" },
    viewport: { tint: { color: "#000000", opacity: 0 }, blur: "00px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#99CC22",
    name: "green leaves",
    background: "green-leaves.jpg",
    navbar: { tint: { color: "#000000", opacity: 0.2 }, blur: "10px" },
    sidebar: { tint: { color: "#000000", opacity: 0.2 }, blur: "10px" },
    playbar: { tint: { color: "#000000", opacity: 0.2 }, blur: "10px" },
    overall: { tint: { color: "#000000", opacity: 0.5 }, blur: "10px" },
    viewport: { tint: { color: "#000000", opacity: 0 }, blur: "00px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#AA53BB",
    name: "violet flowers",
    background: "violet-flowers.jpg",
    navbar: { tint: { color: "#000000", opacity: 0.2 }, blur: "10px" },
    sidebar: { tint: { color: "#000000", opacity: 0.2 }, blur: "10px" },
    playbar: { tint: { color: "#000000", opacity: 0.2 }, blur: "10px" },
    overall: { tint: { color: "#202020", opacity: 0.8 }, blur: "10px" },
    viewport: { tint: { color: "#000000", opacity: 0.0 }, blur: "00px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#82FFC9",
    name: "kuroshitsuji",
    background: "kuroshitsuji.png",
    navbar: { tint: { color: "#000000", opacity: 0.3 }, blur: "10px" },
    sidebar: { tint: { color: "#000000", opacity: 0.3 }, blur: "10px" },
    playbar: { tint: { color: "#000000", opacity: 0.3 }, blur: "10px" },
    overall: { tint: { color: "#000000", opacity: 0.5 }, blur: "5px" },
    viewport: { tint: { color: "#000000", opacity: 0 }, blur: "00px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#9988FF",
    name: "purple blue leaves",
    background: "purple-blue-leaves.png",
    navbar: { tint: { color: "#000000", opacity: 0.3 }, blur: "10px" },
    sidebar: { tint: { color: "#000000", opacity: 0.3 }, blur: "10px" },
    playbar: { tint: { color: "#000000", opacity: 0.3 }, blur: "10px" },
    overall: { tint: { color: "#000000", opacity: 0.5 }, blur: "8px" },
    viewport: { tint: { color: "#000000", opacity: 0 }, blur: "00px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#AA88CC",
    name: "boobs",
    background: "https://cdn.hentaigifz.com/82570/anime-boobs.gif",
    navbar: { tint: { color: "#000000", opacity: 0.3 }, blur: "10px" },
    sidebar: { tint: { color: "#000000", opacity: 0.3 }, blur: "10px" },
    playbar: { tint: { color: "#000000", opacity: 0.3 }, blur: "10px" },
    overall: { tint: { color: "#000000", opacity: 0.5 }, blur: "12px" },
    viewport: { tint: { color: "#000000", opacity: 0 }, blur: "00px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#FF2222",
    name: "red guitarist",
    background: "red-guitarist.png",
    navbar: { tint: { color: "#000000", opacity: 0.4 }, blur: "10px" },
    sidebar: { tint: { color: "#000000", opacity: 0.4 }, blur: "10px" },
    playbar: { tint: { color: "#000000", opacity: 0.4 }, blur: "10px" },
    overall: { tint: { color: "#0a0a0a85", opacity: 0.5 }, blur: "10px" },
    viewport: { tint: { color: "#000000", opacity: 0.0 }, blur: "00px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#83BDF4",
    name: "sakata gintoki",
    background: "sakata-gintoki.jpg",
    navbar: { tint: { color: "#83BDF4", opacity: 0.05 }, blur: "10px" },
    sidebar: { tint: { color: "#83BDF4", opacity: 0.05 }, blur: "10px" },
    playbar: { tint: { color: "#83BDF4", opacity: 0.05 }, blur: "10px" },
    overall: { tint: { color: "#000000", opacity: 0.7 }, blur: "10px" },
    viewport: { tint: { color: "#000000", opacity: 0.0 }, blur: "00px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#83BDF4CC",
    name: "sakata gintoki 2",
    background: "https://images7.alphacoders.com/137/thumb-1920-1374435.png",
    navbar: { tint: { color: "#83BDF4", opacity: 0.05 }, blur: "0px" },
    sidebar: { tint: { color: "#83BDF4", opacity: 0.05 }, blur: "0px" },
    playbar: { tint: { color: "#83BDF4", opacity: 0.05 }, blur: "0px" },
    overall: { tint: { color: "#000000", opacity: 0.7 }, blur: "0px" },
    viewport: { tint: { color: "#000000", opacity: 0.0 }, blur: "0px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#F4BF50",
    name: "sakata kintoki 3",
    background: "https://images5.alphacoders.com/113/thumb-1920-1137590.png",
    navbar: { tint: { color: "#F4BF50", opacity: 0.05 }, blur: "00px" },
    sidebar: { tint: { color: "#F4BF50", opacity: 0.05 }, blur: "00px" },
    playbar: { tint: { color: "#F4BF50", opacity: 0.05 }, blur: "00px" },
    overall: { tint: { color: "#000000", opacity: 0.7 }, blur: "00px" },
    viewport: { tint: { color: "#000000", opacity: 0.0 }, blur: "00px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#F4BF50",
    name: "sakata kintoki",
    background: "sakata-kintoki.png",
    navbar: { tint: { color: "#F4BF50", opacity: 0.05 }, blur: "10px" },
    sidebar: { tint: { color: "#F4BF50", opacity: 0.05 }, blur: "10px" },
    playbar: { tint: { color: "#F4BF50", opacity: 0.05 }, blur: "10px" },
    overall: { tint: { color: "#000000", opacity: 0.7 }, blur: "10px" },
    viewport: { tint: { color: "#000000", opacity: 0.0 }, blur: "00px" },
  },

  {
    preview: "",
    type: "dark",
    accent: "#82FFC9",
    name: "emerald",
    background: "emerald.png",
    navbar: { tint: { color: "#000000", opacity: 0.3 }, blur: "5px" },
    sidebar: { tint: { color: "#000000", opacity: 0.3 }, blur: "5px" },
    playbar: { tint: { color: "#000000", opacity: 0.3 }, blur: "5px" },
    overall: { tint: { color: "#000000", opacity: 0.5 }, blur: "0px" },
    viewport: { tint: { color: "#000000", opacity: 0.1 }, blur: "00px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#ffffff",
    name: "skeleton",
    background: "skeleton.png",
    navbar: { tint: { color: "#000000", opacity: 0.25 }, blur: "0px" },
    sidebar: { tint: { color: "#000000", opacity: 0.25 }, blur: "0px" },
    playbar: { tint: { color: "#000000", opacity: 0.25 }, blur: "0px" },
    overall: { tint: { color: "#000000", opacity: 0.75 }, blur: "0px" },
    viewport: { tint: { color: "#000000", opacity: 0 }, blur: "00px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#e27ca8",
    name: "sakura",
    background: "sakura.png",
    navbar: { tint: { color: "#000000", opacity: 0.2 }, blur: "3px" },
    sidebar: { tint: { color: "#000000", opacity: 0.2 }, blur: "3px" },
    playbar: { tint: { color: "#000000", opacity: 0.2 }, blur: "3px" },
    overall: { tint: { color: "#000000", opacity: 0.5 }, blur: "6px" },
    viewport: { tint: { color: "#000000", opacity: 0 }, blur: "00px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#bb86df",
    name: "money",
    background: "money.png",
    navbar: { tint: { color: "#050005", opacity: 0.3 }, blur: "5px" },
    sidebar: { tint: { color: "#050005", opacity: 0.3 }, blur: "5px" },
    playbar: { tint: { color: "#050005", opacity: 0.3 }, blur: "5px" },
    overall: { tint: { color: "#150024", opacity: 0.6 }, blur: "0px" },
    viewport: { tint: { color: "#000000", opacity: 0.1 }, blur: "2px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#9695f0",
    name: "blurple eyes",
    background: "eyes.png",
    navbar: { tint: { color: "#000000", opacity: 0.3 }, blur: "0px" },
    sidebar: { tint: { color: "#000000", opacity: 0.3 }, blur: "0px" },
    playbar: { tint: { color: "#000000", opacity: 0.3 }, blur: "0px" },
    overall: { tint: { color: "#000000", opacity: 0.5 }, blur: "0px" },
    viewport: { tint: { color: "#000000", opacity: 0.0 }, blur: "0px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#e79bdb",
    name: "pink mountains",
    background: "pink-mount.png",
    navbar: { tint: { color: "#000000", opacity: 0.4 }, blur: "0px" },
    sidebar: { tint: { color: "#000000", opacity: 0.4 }, blur: "0px" },
    playbar: { tint: { color: "#000000", opacity: 0.4 }, blur: "0px" },
    overall: { tint: { color: "#000000", opacity: 0.4 }, blur: "0px" },
    viewport: { tint: { color: "#000000", opacity: 0.2 }, blur: "0px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#B4B886",
    name: "forest",
    background: "forest.gif",
    navbar: { tint: { color: "#000000", opacity: 0.4 }, blur: "0px" },
    sidebar: { tint: { color: "#000000", opacity: 0.4 }, blur: "0px" },
    playbar: { tint: { color: "#000000", opacity: 0.4 }, blur: "0px" },
    overall: { tint: { color: "#000000", opacity: 0.4 }, blur: "0px" },
    viewport: { tint: { color: "#000000", opacity: 0.2 }, blur: "0px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#83d4fac4",
    name: "blue forest",
    background: "blue-forest.png",
    navbar: { tint: { color: "#111115", opacity: 0.4 }, blur: "0px" },
    sidebar: { tint: { color: "#111115", opacity: 0.4 }, blur: "0px" },
    playbar: { tint: { color: "#111115", opacity: 0.4 }, blur: "0px" },
    overall: { tint: { color: "#000000", opacity: 0.4 }, blur: "0px" },
    viewport: { tint: { color: "#000000", opacity: 0.2 }, blur: "0px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#0bff71c4",
    name: "zoro",
    background: "https://www.wallsnapy.com/img_gallery/one-piece-zoro-minimal-dark-emerald-background-957276.jpg",
    navbar: { tint: { color: "#000000", opacity: 0.4 }, blur: "0px" },
    sidebar: { tint: { color: "#000000", opacity: 0.4 }, blur: "0px" },
    playbar: { tint: { color: "#000000", opacity: 0.4 }, blur: "0px" },
    overall: { tint: { color: "#000000", opacity: 0.8 }, blur: "0px" },
    viewport: { tint: { color: "#000000", opacity: 0.0 }, blur: "0px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#aeb3b0",
    name: "undertaker",
    background: "und.jpg",
    navbar: { tint: { color: "#000000", opacity: 0.4 }, blur: "0px" },
    sidebar: { tint: { color: "#000000", opacity: 0.4 }, blur: "0px" },
    playbar: { tint: { color: "#000000", opacity: 0.4 }, blur: "0px" },
    overall: { tint: { color: "#000000", opacity: 0.8 }, blur: "0px" },
    viewport: { tint: { color: "#000000", opacity: 0.0 }, blur: "0px" },
  },
  {
    preview: "",
    type: "dark",
    accent: "#7dbe84",
    name: "lithe",
    background: "lithe.jpg",
    navbar: { tint: { color: "#000000", opacity: 0.4 }, blur: "0px" },
    sidebar: { tint: { color: "#000000", opacity: 0.4 }, blur: "0px" },
    playbar: { tint: { color: "#000000", opacity: 0.4 }, blur: "0px" },
    overall: { tint: { color: "#000000", opacity: 0.5 }, blur: "0px" },
    viewport: { tint: { color: "#000000", opacity: 0.0 }, blur: "0px" },
  },
] satisfies Theme[];

export const themeStore = createGlobalStore<(typeof themes)[number]>(themes[Number(localStorage.getItem("theme")) || 0]!);
